### ISSUE TITLE
Protobuf assembly refernece missing

### ISSUE THREAD

**Issue by LincRsoftware** [BananaHemic/Mumble-Unity#61]
Assets\Mumble-Unity\Runtime\Scripts\MumbleTCPConnection.cs(2,7): error CS0246: The type or namespace name 'ProtoBuf' could not be found (are you missing a using directive or an assembly reference?)

Hi there I have tried everything from installing protobuf packages to recloning but cannot seem to get the protobuf reference.

Any ideas? thanks guys

**Comment by Bananahavoc** [comment]
Protobuf should be included by a nuget package. Can you see if that package is installed? What Unity version are you in?

**Comment by LincRsoftware** [comment]
Thanks for the fast response! 

So it is installed (protobuf-net), however its as if the Protobuf assemblies are missing
My unity version is 2022.3.26f1
Ive managed to get one of your scripts working in a solo project (with the Protobuf-net working) but as soon as i try to git clone into the assets folder the project cant seem to find the protobuf

Is it possible im git cloning into the wrong spot? 
Im cloning into the assets folder itself 

Also another thought was that I was maybe my project is referencing the wrong .NET framework, currently 2.1 i think

Final point, does it need to be protobuf-net 2.4.8?

Thanks again for getting back to me mate :)

<img width="997" alt="Image" src="https://github.com/user-attachments/assets/4e305ef4-a6d6-45c1-a932-b9e040ea7bdb" />

**Comment by Bananahavoc** [comment]
Hmm, not sure why it's not finding protobuf. Cloning into the Assets folder is the expected way to install it.
I suspect that something changed in Unity's package system since I last worked with Unity which has been a few years at this point.

I would recommend just building the protobuf-net.dll file and copying it over. Sorry I couldn't be of more help, there's definitely an easier solution with the package system

**Comment by LincRsoftware** [comment]
Thanks again man, 

Still no success after trying a few more things. 
Really wierd bug that if I do a fresh install of proto in the visaul studio nuget manager, the intellisense kicks in and i have 0 errors and can even compile. 
BUT when I reopen Unity its refreshes and loses the reference and i get 500 errors as listed in the previous photo.
Been at it for a few days now and might have to give up and find another solution for our Comms software.

Thanks a lot Banana 
Apprieciate the help

**Comment by Bananahavoc** [comment]
The error is from the package changes that @bdovaz added. I don't really understand how the package system works (and thus should probably not have accepted that merge request, sorry!) Unless bdovaz is able to help, your best bet is to use commit [1b20eba89ef3f77f5fd87b09afa2676a883c9c02](https://github.com/BananaHemic/Mumble-Unity/commit/1b20eba89ef3f77f5fd87b09afa2676a883c9c02)

Just run `git checkout https://github.com/BananaHemic/Mumble-Unity/commit/1b20eba89ef3f77f5fd87b09afa2676a883c9c02 -f`

**Comment by bdovaz** [comment]
By the end of this week maybe I can help

**Comment by bdovaz** [comment]
I honestly do not understand what problems there are in this issue or in this other https://github.com/BananaHemic/Mumble-Unity/issues/59 which is why the instructions were changed again https://github.com/BananaHemic/Mumble-Unity/commit/889953ca62724ff1fcc3ed77d0e7eb2e2c54165c:

In this example project you can see how with the instructions removed in that PR, it can be installed perfectly without compilation errors:

[My project.zip](https://github.com/user-attachments/files/18809584/My.project.zip)

**Comment by Bananahavoc** [comment]
Thanks @bdovaz your solution is working. I updated the readme to include both your package installation and pointed to where you can download the protobuf dll for people who want to do a manual install.

@LincRsoftware I think your best bet would be to download protobuf dll from [here](https://github.com/BananaHemic/Mumble-Unity/blob/per-speaker-codec/protobuf-net.dll) and see if it solves your problem

**Comment by Karasamazu** [comment]
Hello. I just cloned the repo and still get an protobuf not found error:
...
If the 32 bit overlay library fails to compile, make sure the requirements are installed ("g++-multilib" package on Debian-based distributions).

-- Qt6 component found: Core | Version: 6.4.2
-- Qt6 component found: Network | Version: 6.4.2
-- Qt6 component found: Xml | Version: 6.4.2
-- OpenSSL component found: Crypto | Version: 3.0.13
-- OpenSSL component found: SSL | Version: 3.0.13
CMake Error at cmake/pkg-utils.cmake:124 (message):
  Protobuf not found
Call Stack (most recent call first):
  src/CMakeLists.txt:37 (find_pkg)
...

So I double checked if i had really installed the dependencies (executed the command from the wiki), and I did, but nevertheless the package was not installed. I had to manually again install it separate like this: sudo apt-get install protobuf-compiler
